[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
# bonk-spl = "GwAJcJ8fGBq13nQXWZv5zC1MsLHDjxmWRZhDe27Jypn"
snake_game = "369pQL1kJBnXt1LNUDWJLJ3PytabHM5JDgTiJmtAb9en"

[programs.devnet]
snake_game = "8xkQtyQi8MhfBksFXLvEjVzJcbpjyZanUEsXinvyF4ty"


[registry]
url = "https://api.apr.dev"

[provider.localnet]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[provider.devnet]
cluster = "devnet"
wallet = "~/workspace/pixelbrawlgames.com/gameme/snake-game/deploy-keypair.json"


[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
